---
title: "Untitled"
author: "Margarita Orlova"
date: "October 28, 2018"
output: html_document
---

```{r}
Metropolis <- function(c,iteration){ #Setting starting value, constant c and number of iteration
  fi=runif(1,0,1)
  chain = array(dim=c(iteration+1,1))
  chain[1] = fi
  for (i in 1:iteration){
    proposal = rbeta(1,c*chain[i],c*(1-chain[i]))
    acceptance_ratio = (dbeta(proposal,6,4)/dbeta(proposal,c*chain[i],c*(1-chain[i])))/(dbeta(chain[i],6,4)/dbeta(chain[i],c*proposal,c*(1-proposal)))
    if (runif(1) < acceptance_ratio){
      chain[i+1,] = proposal}
    else{
      chain[i+1,] = chain[i,]
      }
  }
  return(chain)
}

x <- Metropolis(1,10000)

```


```{r}
fi=0.5
c=1
start_value = rbeta(1,c*fi,c*(1-fi))
chain = array(dim=c(2,1))
acceptance_ratio=(dbeta(start_value,6,4)/dbeta(start_value,c*fi,c*(1-fi)))/(dbeta(fi,6,4)/dbeta(fi,c*start_value,c*(1-start_value)))
if (runif(1) < acceptance_ratio){
            chain[i+2,] = proposal
        }else{
            chain[i+1,] = chain[i,]
start_value
acceptance_ratio

```

